import { spawn } from 'node:child_process';
const child = spawn(process.execPath, ['scripts/inventory-agent/antigravity_inventory_mcp.mjs'], { stdio: ['pipe', 'pipe', 'pipe'] });
let output = '';
child.stdout.on('data', (chunk) => { output += chunk.toString(); });
child.stderr.on('data', (chunk) => process.stderr.write(chunk));
const send = (id, method, params = {}) => child.stdin.write(`${JSON.stringify({ jsonrpc: '2.0', id, method, params })}\n`);
send(1, 'initialize');
send(2, 'tools/list');
send(3, 'tools/call', { name: 'inventory_review_status', arguments: {} });
send(4, 'tools/call', { name: 'inventory_get_pending_clusters', arguments: { limit: 1 } });
send(5, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-0001', sameProduct: true, confidence: 0.95, reason: 'Ambas imágenes muestran el mismo anillo de oro rosa con morganita y halo de diamantes.' } });
send(6, 'tools/call', { name: 'inventory_record_error', arguments: { node: 'antigravity.visual-review', error: 'CLI timeout after 90 seconds reviewing reviewed-cluster-0016 contact sheet', context: { clusterId: 'reviewed-cluster-0016', retryable: true } } });
send(7, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-0016', sameProduct: true, confidence: 0.95, reason: 'Todas muestran una cadena de oro con eslabones idénticos y cierres consistentes.' } });
send(8, 'tools/call', { name: 'inventory_record_error', arguments: { node: 'antigravity.visual-review', error: 'CLI timeout after 120 seconds reviewing reviewed-cluster-0034 contact sheet', context: { clusterId: 'reviewed-cluster-0034', retryable: true } } });
send(9, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-1124', sameProduct: true, confidence: 0.98, reason: 'Ambas fotos muestran la misma mano con las mismas joyas y manicura.', source: 'google-ai-studio' } });
send(10, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-0467', sameProduct: true, confidence: 0.95, reason: 'Misma pulsera de cadena de eslabones barbados; coinciden broche, etiqueta y proporciones.', source: 'google-ai-studio' } });
send(11, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-0458', sameProduct: false, confidence: 0.95, reason: 'Los eslabones y el grosor de ambas cadenas son claramente diferentes.', source: 'google-ai-studio' } });
send(12, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-0764', sameProduct: true, confidence: 0.98, reason: 'Ambas fotos muestran la misma cadena de oro en el mismo busto de exhibición.', source: 'google-ai-studio' } });
send(13, 'tools/call', { name: 'inventory_record_review', arguments: { clusterId: 'reviewed-cluster-0415', sameProduct: false, confidence: 0.98, reason: 'Los diseños de los anillos son totalmente distintos entre ambas imágenes.', source: 'google-ai-studio' } });
setTimeout(() => { process.stdout.write(output); child.kill(); }, 3000);
